services:
  links-api:
    image: mcarr823/links-api:latest
    container_name: links-api
    restart: 'unless-stopped'
    environment:
      - DB_TYPE=MEMORY
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "-X", "POST", "http://localhost:8080/health"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
