services:
  links-api:
    image: mcarr823/links-api:latest
    container_name: links-api

    # Only used for SQLite
    volumes:
      - ./links.db:/app/data.db

    restart: 'unless-stopped'
    environment:
      - DB_TYPE=SQLITE
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "-X", "POST", "http://localhost:8080/health"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
